name: Verify Label

on:
  pull_request:
    types: [labeled]

jobs:
  install:
    if: github.event.label.name == 'verify'
    uses: rzavadzich/innowise-ci-workflows/.github/workflows/node-setup.yml@main

  e2e:
    needs: install
    if: github.event.label.name == 'verify'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - uses: actions/download-artifact@v4
        with:
          name: node-modules-${{ github.run_id }}
          path: node_modules

      - name: Run E2E tests
        run: npm run test:e2e --if-present
        continue-on-error: true

      - name: Run all tests
        run: npm test
